name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.20.2
      # GA validations
      - run: yarn install --frozen-lockfile
        working-directory: ./ga
      - run: yarn run validate-change
        working-directory: ./ga
      # Preview validations
      - run: yarn install --frozen-lockfile
        working-directory: ./preview
      - run: yarn run validate-change
        working-directory: ./preview
